### PR TITLE
add initial deploy-script & GHA

### PR DESCRIPTION
**Pull request by russHyde**
As written by csgillespie in
[https://github.com/csgillespie/GA-testing/blob/main/deploy-shinyapps-io.R]()

AIMS:
- [x] ensure deploy step fails without secrets
- [x] ensure script is generalised to handle non-"jumpingrivers" usernames
- [x] with correct secrets in place, ensure deployment happens
- [x] ensure deploy step fails with incorrect account-name
- [x] ensure deploy step fails incorrect named env var: SHIYNAPPS_IO_SECRET
- ~~ensure deployment only happens after linting passes (move to issue)~~
- [x] document (in the README)
  - [x] the URL for deployed branches
  - [x] the secrets that are required for basic deployment

MINOR:
- [x] fix linting step: it should fail with lints and pass without
- ~~move deploy script to ./deploy or ./.github/scripts~~ (ignore for now)

### CODE REVIEW

**Comment by csgillespie** [comment]
I think the issue is that you haven't defined the secrets - see in the deploy.R script for details

**Comment by russHyde** [comment]
There is no issue. I've been working on a different project.

**Comment by russHyde** [comment]
AIMS:
- [x] ensure deploy step fails without secrets
- [ ] ensure script is generalised to handle non-"jumpingrivers" usernames
- [ ] ensure deploy step fails with incorrect username
- [ ] ensure deployment only happens after linting passes
- [ ] with correct secrets in place, ensure deployment happens
- [ ] document
  - [ ] the URL for deployed branches
  - [ ] the secrets that are required for basic deployment
  - [ ] 

MINOR:
- [x] fix linting step: it should fail with lints and pass without

**Comment by russHyde** [comment]
Noted that two deployments happen: one to "<URL_PREFIX>-<branch-name>" and one to "<URL_PREFIX>-NA"

**Pull request merged**
